### ISSUE TITLE
Mixed-case symbols

### ISSUE THREAD

**Issue by lassik** [eratosthenesia/lispc#12]
How does one call C functions with mixed-case names? The code generator turns both `@ftglCreatePixmapFont` and `|@ftglCreatePixmapFont|` into `ftglcreatepixmapfont`.

**Comment by phoe** [comment]
I'd expect kebab-case: `ftgl-create-pixmap-font`.

**Comment by lassik** [comment]
That doesn't preserve case either - `@ftgl-Create-Pixmap-Font` turns into `ftgl_create_pixmap_font`.

**Comment by eratosthenesia** [comment]
Huh. I must have missed that. Let me take a look and I'll get back to you.
I might have to add something in.

>

**Comment by eratosthenesia** [comment]
Okay, I figured it out. If you do: "ftglCreatePixmapFont", it should work
as expected. So if you want to call it, you'd go

(call "ftglCreatePixmapFont" foo bar)

and it'd compile to:

ftglCreatePixmapFont(foo,bar);

**Comment by eratosthenesia** [comment]
Also, if you do:

(call (%ftgl-create-pixmap-font) foo bar)

it compiles to

ftglCreatePixmapFont(foo,bar);

**Comment by lassik** [comment]
Cool, thanks!
